[
  {
    id: 1,
    name: "Classic Watch",
    description: "A timeless classic watch with a leather band.",
    price: 199.99,
    image: "https://via.placeholder.com/150?text=Watch",
    ratings: 5,
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with excellent sound quality.",
    price: 89.99,
    image: "https://via.placeholder.com/150?text=Speaker",
    ratings: 2,
  },
  {
    id: 3,
    name: "Wireless Earbuds",
    description: "Comfortable wireless earbuds with noise-cancellation.",
    price: 129.99,
    image: "https://via.placeholder.com/150?text=Earbuds",
    ratings: 6,
  },
  {
    id: 4,
    name: "Smartphone Case",
    description: "Durable case for your smartphone with a sleek design.",
    price: 29.99,
    image: "https://via.placeholder.com/150?text=Case",
    ratings: 1,
  },
  {
    id: 5,
    name: "Gaming Mouse",
    description: "High-precision gaming mouse with customizable buttons.",
    price: 69.99,
    image: "https://via.placeholder.com/150?text=Mouse",
    ratings: 9,
  },
  {
    id: 6,
    name: "Laptop Stand",
    description: "Adjustable laptop stand for better ergonomics.",
    price: 49.99,
    image: "https://via.placeholder.com/150?text=Stand",
    ratings: 7,
  },
  {
    id: 7,
    name: "Smartwatch",
    description: "Feature-packed smartwatch with fitness tracking.",
    price: 249.99,
    image: "https://via.placeholder.com/150?text=Smartwatch",
    ratings: 2,
  },
  {
    id: 8,
    name: "Portable Charger",
    description: "Compact power bank to keep your devices charged on the go.",
    price: 39.99,
    image: "https://via.placeholder.com/150?text=Charger",
    ratings: 0,
  },
  {
    id: 9,
    name: "Digital Camera",
    description: "High-resolution digital camera for capturing your moments.",
    price: 499.99,
    image: "https://via.placeholder.com/150?text=Camera",
    ratings: 6,
  },
  {
    id: 10,
    name: "Fitness Tracker",
    description: "Monitor your health and fitness with this tracker.",
    price: 79.99,
    image: "https://via.placeholder.com/150?text=Tracker",
    ratings: 3,
  },
  {
    id: 11,
    name: "Tablet",
    description: "Sleek and powerful tablet with a high-resolution display.",
    price: 299.99,
    image: "https://via.placeholder.com/150?text=Tablet",
    ratings: 8,
  },
  {
    id: 12,
    name: "Noise Cancelling Headphones",
    description: "Experience immersive sound with active noise cancellation.",
    price: 199.99,
    image: "https://via.placeholder.com/150?text=Headphones",
    ratings: 9,
  },
  {
    id: 13,
    name: "4K Monitor",
    description: "Stunning 4K UHD monitor for crystal-clear visuals.",
    price: 399.99,
    image: "https://via.placeholder.com/150?text=Monitor",
    ratings: 10,
  },
  {
    id: 14,
    name: "Mechanical Keyboard",
    description: "Durable mechanical keyboard with customizable keys.",
    price: 109.99,
    image: "https://via.placeholder.com/150?text=Keyboard",
    ratings: 5,
  },
  {
    id: 15,
    name: "Smart Home Hub",
    description: "Control your smart devices with this home hub.",
    price: 149.99,
    image: "https://via.placeholder.com/150?text=HomeHub",
    ratings: 4,
  },
  {
    id: 16,
    name: "VR Headset",
    description:
      "Immersive virtual reality experience for gaming and entertainment.",
    price: 399.99,
    image: "https://via.placeholder.com/150?text=VR+Headset",
    ratings: 7,
  },
  {
    id: 17,
    name: "Wireless Charger",
    description: "Convenient wireless charger for all compatible devices.",
    price: 49.99,
    image: "https://via.placeholder.com/150?text=Wireless+Charger",
    ratings: 6,
  },
  {
    id: 18,
    name: "Action Camera",
    description: "Compact action camera for capturing adventures.",
    price: 149.99,
    image: "https://via.placeholder.com/150?text=Action+Camera",
    ratings: 8,
  },
  {
    id: 19,
    name: "Drone",
    description:
      "High-performance drone with HD camera for aerial photography.",
    price: 599.99,
    image: "https://via.placeholder.com/150?text=Drone",
    ratings: 9,
  },
  {
    id: 20,
    name: "Smart Light Bulb",
    description: "Energy-efficient LED bulb with smart home compatibility.",
    price: 19.99,
    image: "https://via.placeholder.com/150?text=Light+Bulb",
    ratings: 3,
  },
  {
    id: 21,
    name: "Portable Projector",
    description: "Compact projector for on-the-go entertainment.",
    price: 229.99,
    image: "https://via.placeholder.com/150?text=Projector",
    ratings: 7,
  },
  {
    id: 22,
    name: "Gaming Console",
    description: "Next-gen gaming console for immersive gaming experiences.",
    price: 499.99,
    image: "https://via.placeholder.com/150?text=Console",
    ratings: 10,
  },
  {
    id: 23,
    name: "Smart Thermostat",
    description: "Adjust your home temperature with smart scheduling.",
    price: 129.99,
    image: "https://via.placeholder.com/150?text=Thermostat",
    ratings: 5,
  },
  {
    id: 24,
    name: "Electric Scooter",
    description: "Eco-friendly electric scooter for urban commuting.",
    price: 299.99,
    image: "https://via.placeholder.com/150?text=Scooter",
    ratings: 8,
  },
  {
    id: 25,
    name: "Robot Vacuum",
    description: "Effortless cleaning with an automated robot vacuum.",
    price: 199.99,
    image: "https://via.placeholder.com/150?text=Vacuum",
    ratings: 6,
  },
  {
    id: 26,
    name: "Smart Doorbell",
    description: "See and speak to visitors at your door from anywhere.",
    price: 99.99,
    image: "https://via.placeholder.com/150?text=Doorbell",
    ratings: 7,
  },
  {
    id: 27,
    name: "Bluetooth Tracker",
    description: "Keep track of your belongings with this Bluetooth tracker.",
    price: 29.99,
    image: "https://via.placeholder.com/150?text=Tracker",
    ratings: 4,
  },
  {
    id: 28,
    name: "E-Reader",
    description: "Portable e-reader with a glare-free display.",
    price: 119.99,
    image: "https://via.placeholder.com/150?text=E-Reader",
    ratings: 9,
  },
  {
    id: 29,
    name: "Digital Picture Frame",
    description: "Display your favorite photos in a digital frame.",
    price: 59.99,
    image: "https://via.placeholder.com/150?text=Frame",
    ratings: 6,
  },
  {
    id: 30,
    name: "Fitness Dumbbells",
    description: "Adjustable dumbbells for your home workout routine.",
    price: 89.99,
    image: "https://via.placeholder.com/150?text=Dumbbells",
    ratings: 5,
  },
];
